name: Boolean Job Output
on:
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        default: true
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - run: 'true'
    outputs:
      boolean: ${{ inputs.boolean }}
  echo:
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.output.outputs.boolean) }}
    needs:
      - output
    steps:
      - name: echo
        run: echo "${{ needs.output.outputs.boolean }}"
